import type { D1Migration } from '@cloudflare/vitest-pool-workers';

// `cloudflare:test`'s `env` const is typed as `Cloudflare.Env` (see
// worker-configuration.d.ts, generated by `wrangler types`). Merge in the
// one extra binding vitest.config.ts injects that isn't a real wrangler.jsonc
// binding — the migrations list applied in test/apply-migrations.ts.
declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}

export {};
