// @ts-check
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'web/dist/**',
      '.wrangler/**',
      '.tsbuild/**',
      'node_modules/**',
      // Generated by `wrangler types` / `npm run cf-typegen` — not our code.
      'worker-configuration.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // TypeScript's own compiler (npm run typecheck) already catches
      // genuine undefined-identifier bugs, and does so correctly for the
      // ambient runtime globals (Request, URL, crypto, ExecutionContext,
      // Element, ...) that this rule doesn't know about across our two very
      // different runtimes (Workers vs. browser). Redundant with `tsc`,
      // false-positive-prone here.
      'no-undef': 'off',
    },
  },
  {
    // Plain Node scripts (not part of the tsc project graph) — give them
    // Node's ambient globals so `no-undef` doesn't flag console/process.
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: globals.node,
    },
  },
);
