import { Hono } from 'hono';

// `Env` is ambient/global — generated by `wrangler types` into
// worker-configuration.d.ts from wrangler.jsonc's bindings. Regenerate it
// (npm run cf-typegen) whenever bindings change; no hand-written Env type.
export const health = new Hono<{ Bindings: Env }>();

// Touches D1 (not just returns 200) so a deploy with a broken binding or an
// unreachable database shows up here rather than silently passing.
health.get('/', async (c) => {
  const row = await c.env.DB.prepare('select 1 as ok').first<{ ok: number }>();
  return c.json({
    status: row?.ok === 1 ? 'ok' : 'degraded',
    environment: c.env.ENVIRONMENT,
    time: new Date().toISOString(),
  });
});
