// Secrets are set with `wrangler secret put`, never declared in
// wrangler.jsonc, so `wrangler types` cannot see them and the generated
// worker-configuration.d.ts (DO NOT EDIT — it is regenerated by
// `npm run cf-typegen`) leaves them out. They are declaration-merged onto
// the global `Env` interface here instead.
//
// Optional on purpose: an environment without the secret is a supported
// state that must fail with a clear message, not a deployment that assumes
// the secret is present because it was set somewhere else.

interface Env {
  /**
   * Base64 AES-256 key for encrypting stored provider credentials
   * (src/lib/crypto.ts, migrations/0010). App-level infrastructure rather
   * than any user's identity — which is precisely why a global Worker
   * secret is right here and wrong for the credentials themselves.
   *
   * Rotating it invalidates every stored credential; the recovery is that
   * users re-enter them.
   */
  CREDENTIALS_KEY?: string;
}
