// Secrets are set with `wrangler secret put`, never declared in
// wrangler.jsonc, so `wrangler types` cannot see them and the generated
// worker-configuration.d.ts (DO NOT EDIT — it is regenerated by
// `npm run cf-typegen`) leaves them out entirely. They are declaration-
// merged onto the global `Env` interface here instead.
//
// Every one is OPTIONAL on purpose: an environment with the integration
// unconfigured is a normal, supported state, not a deployment error. The
// code that reads these must handle absence and say so, rather than
// assuming a secret is present because it was set somewhere else.

interface Env {
  /**
   * Wise personal API token (`Authorization: Bearer ...`). Read-only usage
   * here, but note the token itself is NOT read-only — Wise personal
   * tokens can also create transfers, so it is a secret in the strong
   * sense and must never be logged or echoed in a response.
   */
  WISE_API_TOKEN?: string;
}
